version: '2'
services:
    users:
        container_name: users
        build: .
        image: users:latest
        ports:
            - "80:80"
        volumes:
            - .:/users
        environment:
            - PORT:80
