version: '3'

services:

  rabbitmq:
    image: 'rabbitmq:3.6-management-alpine'
    ports:
      - '5672:5672'
      - '15672:15672'

  server:
    build: server
    volumes:
      - ./server:/app
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - 80:80

  slave:
    build: slave
    volumes:
      - ./slave:/app
    environment:
      - PYTHONUNBUFFERED=1

  master:
    build: master
    volumes:
      - ./master:/app
    environment:
      - PYTHONUNBUFFERED=1
